[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
description = "A simple task runner for ESP32-C3 project"

[dependencies]
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
toml = "0.8.8"
